# Generated by Django 3.2.3 on 2021-05-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_auto_20210523_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.ManyToManyField(to='viewer.Language'),
        ),
    ]
