# Generated by Django 3.2.3 on 2021-05-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_auto_20210523_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='language',
            new_name='languages',
        ),
    ]
