# Generated by Django 3.2.3 on 2021-05-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watch_list',
            field=models.ManyToManyField(to='viewer.Movie'),
        ),
    ]
