# Generated by Django 3.2.3 on 2021-05-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_profile_watch_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
