# Generated by Django 3.2.3 on 2021-05-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_movie_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='directors', to='viewer.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='stars', to='viewer.Person'),
        ),
    ]
